## Data format

#### Initial order:
    
- Variable name: initial_order_<$pair$>
- Format: Numpy array ( col : attributes )
        0 : {'bid' : 0 ; 'ask' : 1}
        1 : Price 
        2 : Initial Volume

#### Update order:

- Variable name: update_order_<$pair$>
- Format: Numpy array ( col : attributes )
        0 : {'bid' : 1 ; 'ask' : 2}
        1 : price
        2 : remaining volume
        3 : delta volume 
        4 : timestamp
        5 : timestampms
        6 : {'cancel' : 1, 'place' : 2, 'trade' : 3}
        7 : eventId
        
        
        

## Data for BTC / USD pair

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

btcusd_init = pd.read_csv("/Users/syiming/Desktop/SRG/1-12/btcusd_init.csv") # Read initial btcusd order book data

print(btcusd_init.head())

     type     eventId  socket_sequence  \
0  update  5347144785                0   
1  update  5347144785                0   
2  update  5347144785                0   
3  update  5347144785                0   
4  update  5347144785                0   

                                              events  
0  {'type': 'change', 'reason': 'initial', 'price...  
1  {'type': 'change', 'reason': 'initial', 'price...  
2  {'type': 'change', 'reason': 'initial', 'price...  
3  {'type': 'change', 'reason': 'initial', 'price...  
4  {'type': 'change', 'reason': 'initial', 'price...  


In [76]:
# Create dictionary for bid and ask
bidask = {'bid' : 1 , 'ask' : 0}

from ast import literal_eval

# Count lines in btcusd_init
counter = 0
for row in btcusd_init.iterrows():
    if d["delta"] != d["remaining"]:
        print("Delta / Remaining not matched!")
    counter += 1

# Create initial_order: stores the initial order book
# 0 : {'bid' : 0 ; 'ask' : 1}
# 1 : Price 
# 2 : Initial Volume
initial_order_btcusd = np.zeros((counter, 3))
row_num = 0
for row in btcusd_init.iterrows():
    d = literal_eval(row[1]["events"]) # Covert string to dictionary                
    initial_order_btcusd[row_num, 0] = bidask[d['side']] # 0 : {'bid' : 1 ; 'ask' : 0}
    initial_order_btcusd[row_num, 1] = float(d["price"]) # 1 : Price 
    initial_order_btcusd[row_num, 2] = float(d["delta"]) # 2 : Initial Volume
    row_num += 1
print(initial_order_btcusd)

[[1.00000000e+00 1.00000000e-02 1.91642102e+05]
 [1.00000000e+00 2.00000000e-02 2.29595000e+04]
 [1.00000000e+00 3.00000000e-02 3.30000000e+01]
 ...
 [0.00000000e+00 9.99999000e+05 1.81884000e-02]
 [0.00000000e+00 9.99999420e+05 5.00000000e+00]
 [0.00000000e+00 1.00000000e+06 2.00000000e-03]]


In [55]:
btcusd_update = pd.read_csv("/Users/syiming/Desktop/SRG/1-12/btcusd.csv") # Read the update data

print(btcusd_update.head())

   Unnamed: 0    type     eventId   timestamp    timestampms  socket_sequence  \
0           0  update  5347144857  1547321049  1547321049820                1   
1           1  update  5347144867  1547321050  1547321050110                2   
2           2  update  5347144944  1547321053  1547321053890                3   
3           3  update  5347144947  1547321054  1547321054006                4   
4           4  update  5347144951  1547321054  1547321054032                5   

  event_type side    price  remaining     delta  reason  
0     change  ask  3629.26   1.396807  1.396807   place  
1     change  ask  3652.60   0.620000  0.620000   place  
2     change  bid  3625.83   0.000000 -3.700000  cancel  
3     change  bid  3626.83   0.000000 -6.857100  cancel  
4     change  bid  3624.78   6.889100  6.889100   place  


In [77]:
# Create a dictionary for reason
reason = {'cancel' : 1, 'place' : 2, 'trade' : 3}

# Create numpy array for update
# 0 : {'bid' : 1 ; 'ask' : 2}
# 1 : price
# 2 : remaining volume
# 3 : delta volume 
# 4 : timestamp
# 5 : timestampms
# 6 : reason
# 7 : eventId

# Count lines in btcusd_init
counter = 0
for row in btcusd_update.iterrows():
    counter += 1
    
update_order_btcusd = np.zeros((counter, 8))
row_num = 0    
for row in btcusd_update.iterrows():
    update_order_btcusd[row_num, 0] = bidask[row[1]['side']]
    update_order_btcusd[row_num, 1] = row[1]['price']
    update_order_btcusd[row_num, 2] = row[1]['remaining']
    update_order_btcusd[row_num, 3] = row[1]['delta']
    update_order_btcusd[row_num, 4] = row[1]['timestamp']
    update_order_btcusd[row_num, 5] = row[1]['timestampms']
    update_order_btcusd[row_num, 6] = reason[row[1]['reason']]
    update_order_btcusd[row_num, 7] = row[1]['eventId']
    row_num += 1
print(update_order_btcusd)

[[0.00000000e+00 3.62926000e+03 1.39680691e+00 ... 1.54732105e+12
  2.00000000e+00 5.34714486e+09]
 [0.00000000e+00 3.65260000e+03 6.20000000e-01 ... 1.54732105e+12
  2.00000000e+00 5.34714487e+09]
 [1.00000000e+00 3.62583000e+03 0.00000000e+00 ... 1.54732105e+12
  1.00000000e+00 5.34714494e+09]
 ...
 [0.00000000e+00 3.62085000e+03 1.00000000e+00 ... 1.54733924e+12
  2.00000000e+00 5.34813046e+09]
 [1.00000000e+00 3.60880000e+03 0.00000000e+00 ... 1.54733924e+12
  1.00000000e+00 5.34813048e+09]
 [0.00000000e+00 3.62085000e+03 0.00000000e+00 ... 1.54733924e+12
  1.00000000e+00 5.34813053e+09]]


In [78]:
np.save('init_order_btcusd.npy', initial_order_btcusd)

In [79]:
np.save('update_order_btcusd.npy', update_order_btcusd)